### ISSUE TITLE
Welcome/Home Screen -- Sprint 1

### ISSUE THREAD

**Issue by pratyush1718** [cse110-sp23-group30/cse110-sp23-group30#24]
Implement baseline version of home screen.
- [ ] Add static image as background for home screen
- [ ] Add "Play" Button that directs to Food Selection Screen
- [ ] Add "Settings" Button that directs to an empty pop up for now
- [ ] Add "Instructions/How to Play" button that directs to instructions screen
- [ ] Check for linting/upload images of home screen in PR

**Comment by ry4nwong** [comment]
Created a baseline skeleton for welcome/home screen
Added play button and instructions button that will route to respective pages
Added settings popup to be implemented later
Static background image TBD
