### ISSUE TITLE
Instructions Screen -- Sprint 1

### ISSUE THREAD

**Issue by pratyush1718** [cse110-sp23-group30/cse110-sp23-group30#25]
Implement baseline version of Instructions screen.
- [x] Create an ordered list that explains how to play the game (for now, no images are necessary but this will change as we continue to work on the issue)
- [x] Add arrows to toggle between each instruction (to create a tutorial-like feel to instructions screen)
- [x] Have button to "go back" to home screen
- [x] Have button to proceed playing that directs to cart screen

**Comment by pthaha** [comment]
Make the back bone for instruction screen
Functionality to other screens will be implemented next sprint
Styles determined in later meeting
Set up classes for main componts for easy changes
