### ISSUE TITLE
Food Selection -- Bowl Screen -- Sprint 1

### ISSUE THREAD

**Issue by pratyush1718** [cse110-sp23-group30/cse110-sp23-group30#26]
Implement baseline version of food selection screen that allows user to create their bowl.
- [x] Add a div for each of the following: base (Rice, noodles, etc), protein, toppings, sides
- [x] For each div, include AT LEAST 3 "card-style" (you can lift this from lab 6) food selection items
- [x] for now, no images are necessary and names of food items can be strings. As we continue to work on this, we will eventually use localStorage API.
- [x] Have button/section to "order more" and redirect to cart screen

**Comment by GeorgioFe** [comment]
Created the bowl screen which allows users to customize their meals by selecting a base, protein, toppings, and sides. Implemented the necessary features, including creating div elements for each component, populating them with at least three "card-style" food selection items, and adding a button or section for users to order more items. I worked on the HTML structure, CSS styling, and JavaScript functionality to bring the bowl screen to life. The next steps include integrating the localStorage API, enhancing the user interface with images, dynamically updating the cart screen, and conducting user testing for a seamless user experience.
