### ISSUE TITLE
Cart Screen -- Sprint 1

### ISSUE THREAD

**Issue by pratyush1718** [cse110-sp23-group30/cse110-sp23-group30#28]
- [x] Allow user to view their current cart (which lists all the foods they have ordered) 
- [x] Allow user to clear cart
- [x] Have button to add a plate, and direct to Food Selection -- Plate Screen
- [x] Have button to add a bowl, and direct to Food Selection -- Bowl Screen
- [x] Have button to finalize order and direct to fortune cookie animation screen

**Comment by e81786** [comment]
Created a very basic cart screen with sample cart items.
Finished the basic HTML and JS, but have yet to implement a working version of everything as I'm not sure how to implement items from other screens yet, or how to get an array from another screen to the cart screen.
Have yet to implement the delete button either as I'm waiting for actual list items, so I know how to work around those.

No CSS implementation yet, not sure what theme to base it off of yet.
