### ISSUE TITLE
Fortune Cookie Animation Screen -- Sprint 1

### ISSUE THREAD

**Issue by pratyush1718** [cse110-sp23-group30/cse110-sp23-group30#29]
- [x] Add Fortune cookie image
- [x] Add basic "shake" animation
- [x] Have fortune cookie display a message (for now, you can just have an array called messages and randomly pick from that)
- [x] Have button to go back to home
- [x] Have button to restart game that redirects to cart screen

**Comment by Jackson-Wang-0** [comment]
Made the backbone of the cookie animation screen
styles will be determined later
added animation for shake button and will be modified later on depending on functions
