### ISSUE TITLE
Incorporate linting -- sprint 1&2

### ISSUE THREAD

**Issue by jaemin-capslock** [cse110-sp23-group30/cse110-sp23-group30#31]
Linter is primarily a formatting service that can be run through the command line or as a VSCode extension.

- [x] Sprint 1: Write a .yml file under workflow directory that runs linter through all (or selected) .js, files and fix the style of current js files.
- [x] Sprint 2: Edit the .yml file under workflow directory that runs linter through all (or selected) .html, .css, .md, .json, .yml files, and fix the style of current ones.
- [x] Sprint 1&2: Write config files for more detailed styles other than the default ones and include it when running.

**Comment by pratyush1718** [comment]
#100
