### ISSUE TITLE
Incorporate Linting

### ISSUE THREAD

**Issue by jaemin-capslock** [cse110-sp23-group30/cse110-sp23-group30#32]
- [x] Research different linting APIs for HTML/CSS/JS
- [x] Create .yml for Github Actions and integrate into the workflow

**Comment by idmkris** [comment]
ESLint API: ESLint is a widely used JavaScript linter. It provides an API that allows you to programmatically analyze JavaScript code and get linting results. You can use the ESLint API to build custom linting integrations or create tools that leverage ESLint's functionality.
Stylelint API: Stylelint is a CSS linter that helps you enforce consistent coding styles and detect errors in CSS code. It also provides an API that allows you to integrate Stylelint into your applications or build custom linting solutions for CSS.
Pylint API: Pylint is a Python linter that checks for programming errors, helps enforce coding standards, and provides code analysis and recommendations. It offers an API that enables you to use Pylint programmatically, allowing you to perform linting on Python code and retrieve linting results.
SonarQube API: SonarQube is a popular code quality platform that supports multiple programming languages. It provides a comprehensive set of code analysis tools, including linting capabilities. SonarQube exposes a REST API that allows you to integrate with its linting features and retrieve analysis results.

**Comment by idmkris** [comment]
Having a linting checking our code really helps the overall development of our program. Linting tools provide quick feedback by highlighting potential issues in your code. This allows us to fix problems early on and avoid spending time on debugging or troubleshooting later. Linters also provide suggestions and recommendations to improve our code, which can help us write better code faster. It ensures that all team members adhere to the same coding standards and practices. It reduces inconsistencies and makes the codebase more cohesive.
